# pdf_exporter.py
# Purpose: Generate a downloadable PDF report of the analysis results.
# Library: fpdf2 — simple, no external dependencies

from fpdf import FPDF
# FPDF — class jo PDF document represent karti hai
# fpdf2 library se aati hai — pip install fpdf2

import datetime
# datetime — current date/time ke liye


class AdReport(FPDF):
    # AdReport — FPDF class ko extend kar rahe hain
    # Inheritance — FPDF ke saare methods available hain
    # Plus humari custom header/footer methods

    def header(self):
        # header() — FPDF automatically har page pe call karta hai
        # Override karke apna custom header daal sakte hain

        self.set_font("Helvetica", "B", 16)
        # set_font(family, style, size)
        # "B" = Bold, "I" = Italic, "BI" = Bold Italic, "" = Regular

        self.set_text_color(83, 74, 183)
        # RGB color — purple (same as our UI theme)
        # set_text_color(R, G, B) — 0 to 255

        self.cell(0, 10, "Ad Genius Pro — Analysis Report", align="C")
        # cell(width, height, text, align)
        # width=0 — full page width
        # align="C" — center

        self.ln(5)
        # ln(height) — line break, move down by height mm

        self.set_draw_color(83, 74, 183)
        # set_draw_color — line/border color

        self.line(10, self.get_y(), 200, self.get_y())
        # Draw horizontal line across page
        # line(x1, y1, x2, y2)
        # get_y() — current Y position

        self.ln(8)

    def footer(self):
        # footer() — FPDF automatically har page ke bottom pe call karta hai

        self.set_y(-15)
        # set_y(-15) — page ke bottom se 15mm upar jao
        # negative value = bottom se measure karo

        self.set_font("Helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        # Gray color for footer

        self.cell(0, 10, f"Page {self.page_no()} | Generated by Ad Genius Pro", align="C")
        # page_no() — current page number


def generate_report(
    product_description: str,
    original_ad:         str,
    score_data:          dict,
    gaps:                list,
    rewritten_ad:        str,
    changes_made:        str
) -> bytes:
    """
    Generate complete PDF report and return as bytes.

    Parameters:
        product_description : str  — user ka product
        original_ad         : str  — original ad copy
        score_data          : dict — from scoring engine
        gaps                : list — from analyst agent
        rewritten_ad        : str  — from builder agent
        changes_made        : str  — explanation of changes

    Returns:
        bytes — PDF file as bytes (for Streamlit download button)
    """

    pdf = AdReport()
    # Create new PDF document using our custom class

    pdf.set_auto_page_break(auto=True, margin=15)
    # auto=True — automatically new page add karo jab content overflow ho
    # margin=15 — bottom se 15mm pehle new page shuru karo

    pdf.add_page()
    # First page add karo

    pdf.set_margins(15, 20, 15)
    # set_margins(left, top, right) — page margins in mm

    # ==========================================
    # SECTION 1: Report metadata
    # ==========================================

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)

    now = datetime.datetime.now().strftime("%B %d, %Y at %I:%M %p")
    # strftime — format date as string
    # %B = full month name, %d = day, %Y = year
    # %I = 12-hour, %M = minutes, %p = AM/PM

    pdf.cell(0, 6, f"Generated: {now}", align="R")
    # align="R" — right align
    pdf.ln(3)
    pdf.cell(0, 6, f"Product: {product_description}", align="R")
    pdf.ln(10)

    # ==========================================
    # SECTION 2: Viral Score
    # ==========================================

    _section_header(pdf, "Viral Score Analysis")

    # Big score display
    pdf.set_font("Helvetica", "B", 48)
    pdf.set_text_color(83, 74, 183)
    pdf.cell(0, 20, f"{score_data['total_score']}/100", align="C")
    pdf.ln(5)

    # Grade
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(60, 60, 60)
    pdf.cell(0, 8, score_data["grade"], align="C")
    pdf.ln(10)

    # Score breakdown table
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(60, 60, 60)
    pdf.cell(0, 7, "Score Breakdown:", ln=True)
    pdf.ln(2)

    breakdown_labels = {
        "length_score":        "Length Score",
        "hook_strength":       "Hook Strength",
        "sentiment_stability": "Sentiment Stability",
        "keyword_density":     "Keyword Density",
        "clarity":             "Clarity"
    }

    for key, label in breakdown_labels.items():
        value = score_data["breakdown"][key]
        # Draw metric row
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(80, 80, 80)
        pdf.cell(80, 7, label)
        # cell(width, height, text) — no ln means next cell same line

        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(83, 74, 183)
        pdf.cell(20, 7, f"{value}/10")

        # Progress bar — visual representation
        bar_x = pdf.get_x()
        bar_y = pdf.get_y() + 1
        bar_width = 80
        filled = int((value / 10) * bar_width)
        # filled pixels = (score/10) * total_width

        # Background bar (gray)
        pdf.set_fill_color(220, 220, 220)
        pdf.rect(bar_x, bar_y, bar_width, 4, "F")
        # rect(x, y, width, height, style)
        # "F" = filled rectangle

        # Filled bar (purple)
        pdf.set_fill_color(83, 74, 183)
        pdf.rect(bar_x, bar_y, filled, 4, "F")

        pdf.ln(8)

    pdf.ln(5)

    # ==========================================
    # SECTION 3: Original Ad
    # ==========================================

    _section_header(pdf, "Original Ad Copy")
    _text_box(pdf, original_ad, bg_color=(252, 235, 235))
    # Light red background — shows original (needs improvement)
    pdf.ln(5)

    # ==========================================
    # SECTION 4: Gaps Identified
    # ==========================================

    _section_header(pdf, f"Gaps Identified ({len(gaps)} found)")

    severity_colors = {
        "high":   (220, 50,  50),
        "medium": (200, 140, 20),
        "low":    (50,  160, 80)
    }

    for i, gap in enumerate(gaps, 1):
        color = severity_colors.get(gap["severity"], (100, 100, 100))

        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(*color)
        # *color — unpack tuple as separate arguments
        # (220, 50, 50) becomes set_text_color(220, 50, 50)

        pdf.cell(0, 6, f"{i}. [{gap['severity'].upper()}] {gap['gap']}", ln=True)

        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(100, 100, 100)
        pdf.multi_cell(0, 5, f"   Competitors do: {gap['competitor_does']}")
        # multi_cell — auto wraps text to next line if too long
        # cell() does not wrap — multi_cell() does

        pdf.ln(2)

    pdf.ln(5)

    # ==========================================
    # SECTION 5: Rewritten Ad
    # ==========================================

    _section_header(pdf, "Optimized Ad Copy")
    _text_box(pdf, rewritten_ad, bg_color=(225, 245, 238))
    # Light green background — shows improved version
    pdf.ln(5)

    # ==========================================
    # SECTION 6: Changes Made
    # ==========================================

    _section_header(pdf, "Changes Made")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(60, 60, 60)
    pdf.multi_cell(0, 6, changes_made)

    # ==========================================
    # Return PDF as bytes
    # ==========================================

    return pdf.output()
    # output() — returns PDF as bytes
    # Streamlit download button accepts bytes directly


def _section_header(pdf: FPDF, title: str):
    """
    Draw a styled section header.
    Underscore prefix — private helper, only used inside this file.
    """
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(83, 74, 183)
    pdf.set_fill_color(238, 237, 254)
    # Light purple background

    pdf.cell(0, 9, f"  {title}", ln=True, fill=True)
    # fill=True — cell background color use karo
    pdf.ln(4)


def _text_box(pdf: FPDF, text: str, bg_color: tuple):
    """
    Draw text inside a colored box.
    Used for original and rewritten ad display.
    """
    pdf.set_fill_color(*bg_color)
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(40, 40, 40)

    # Draw box manually
    x = pdf.get_x()
    y = pdf.get_y()

    pdf.set_x(15)
    pdf.multi_cell(0, 7, text, fill=True, border=0)
    pdf.ln(2)